# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

# version
version: 2

mkdocs: {}  # tell readthedocs to use mkdocs

python:
  version: 3.7
  install:
  - method: pip
    extra_requirements: ["rtd"]
