#
# https://readthedocs-custom-steps.readthedocs.io/en/latest/
#

# version
version: 2

mkdocs:
  configuration: "docs/mkdocs.yml"

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt
