
name: build tests
on: [push]

jobs:

  test:
    name: "Test package"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - uses: NiklasRosenstein/slap@gha/install/v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with: { python-version: "${{ matrix.python-version }}" }
    - run: slap venv --create tester && slap install --use-venv=tester
    - name: Validate and test
      run: |
        slap release --validate
        slap test --use-venv=tester
        slap install --use-venv=tester
